---
- name: Configure RHEL Linux 7.1 with tomcat domain
  hosts: tomcat
  become: true
  become_user: root
  vars_files:
  # User defined variables for infrastructure
  - infra-vars.yml
  # infrastructure Passwords
  - secrets.yml
  # Common properties. You may not delete this.
  - tomcat-properties.yml
  roles:
   - linux-tomcat
